apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.kube.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 9000