apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api-deployment.yaml
- api-service.yaml
namespace: api
images:
- name: api
  newName: rbiondi/app
  newTag: e82171a24a7668b878e55db87067847c93c6ec77
